// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RegistroPedidosBlazor.DAL;

namespace RegistroPedidosBlazor.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20210227044248_Migracion_Inicial")]
    partial class Migracion_Inicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.3");

            modelBuilder.Entity("RegistroPedidosBlazor.Models.Ordenes", b =>
                {
                    b.Property<int>("OrdenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Monto")
                        .HasColumnType("TEXT");

                    b.Property<int>("SuplidorId")
                        .HasColumnType("INTEGER");

                    b.HasKey("OrdenId");

                    b.ToTable("Ordenes");
                });

            modelBuilder.Entity("RegistroPedidosBlazor.Models.OrdenesDetalle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Cantidad")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Costo")
                        .HasColumnType("TEXT");

                    b.Property<int>("OrdenId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("OrdenId");

                    b.HasIndex("ProductoId");

                    b.ToTable("OrdenesDetalle");
                });

            modelBuilder.Entity("RegistroPedidosBlazor.Models.Productos", b =>
                {
                    b.Property<int>("ProductoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Costo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float>("Inventario")
                        .HasColumnType("REAL");

                    b.HasKey("ProductoId");

                    b.ToTable("Productos");

                    b.HasData(
                        new
                        {
                            ProductoId = 1,
                            Costo = 15m,
                            Descripcion = "Agua",
                            Inventario = 25f
                        },
                        new
                        {
                            ProductoId = 2,
                            Costo = 25m,
                            Descripcion = "Soda",
                            Inventario = 50f
                        },
                        new
                        {
                            ProductoId = 3,
                            Costo = 35m,
                            Descripcion = "Leche",
                            Inventario = 50f
                        },
                        new
                        {
                            ProductoId = 4,
                            Costo = 45m,
                            Descripcion = "Jugo Rica",
                            Inventario = 50f
                        },
                        new
                        {
                            ProductoId = 5,
                            Costo = 45m,
                            Descripcion = "Choco-Rica",
                            Inventario = 50f
                        },
                        new
                        {
                            ProductoId = 6,
                            Costo = 15m,
                            Descripcion = "Batata",
                            Inventario = 50f
                        },
                        new
                        {
                            ProductoId = 7,
                            Costo = 55m,
                            Descripcion = "Manzana",
                            Inventario = 50f
                        });
                });

            modelBuilder.Entity("RegistroPedidosBlazor.Models.Suplidores", b =>
                {
                    b.Property<int>("SuplidorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("SuplidorId");

                    b.ToTable("Suplidores");

                    b.HasData(
                        new
                        {
                            SuplidorId = 1,
                            Nombres = "Juanito Alimaña"
                        },
                        new
                        {
                            SuplidorId = 2,
                            Nombres = "Carmen Stuart"
                        },
                        new
                        {
                            SuplidorId = 3,
                            Nombres = "Pablo Escobar"
                        },
                        new
                        {
                            SuplidorId = 4,
                            Nombres = "David Guetta"
                        },
                        new
                        {
                            SuplidorId = 5,
                            Nombres = "Batata Corp."
                        },
                        new
                        {
                            SuplidorId = 6,
                            Nombres = "Nike"
                        });
                });

            modelBuilder.Entity("RegistroPedidosBlazor.Models.OrdenesDetalle", b =>
                {
                    b.HasOne("RegistroPedidosBlazor.Models.Ordenes", null)
                        .WithMany("Detalle")
                        .HasForeignKey("OrdenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RegistroPedidosBlazor.Models.Productos", "Producto")
                        .WithMany()
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("RegistroPedidosBlazor.Models.Ordenes", b =>
                {
                    b.Navigation("Detalle");
                });
#pragma warning restore 612, 618
        }
    }
}
